In [1]:
import pandas as pd

In [2]:
pd.__version__

'3.0.6'

In [4]:
!wget https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv

--2026-09-26 14:21:22--  https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 635180 (620K) [text/plain]
Saving to: ‘car_fuel_efficiency_2026.csv’

car_fuel_efficiency 100%[===================>] 620.29K  --.-KB/s    in 0.005s

2026-09-26 14:21:22 (121 MB/s) - ‘car_fuel_efficiency_2026.csv’ saved [635180/635180]

In [5]:
df = pd.read_csv("car_fuel_efficiency_2026.csv")

In [6]:
df.count()

model_year             10000
origin                 10000
fuel_type              10000
drivetrain             10000
num_doors              10000
engine_displacement    10000
num_cylinders          10000
horsepower              9123
vehicle_weight         10000
acceleration            9736
fuel_efficiency_mpg    10000
dtype: int64

In [10]:
df['fuel_type'].nunique()

3

In [9]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [11]:
df.groupby('origin').count()

,model_year,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
origin,,,,,,,,,,
Asia,2994,2994,2994,2994,2994,2994,2729,2994,2994,2994
Europe,2804,2804,2804,2804,2804,2804,2561,2804,2540,2804
USA,4202,4202,4202,4202,4202,4202,3833,4202,4202,4202

In [21]:
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

np.float64(41.2)

In [22]:
df['horsepower'].median()

np.float64(254.0)

In [23]:
df['horsepower'].mode()

0    252.0
Name: horsepower, dtype: float64

In [28]:
df['horsepower'] = df['horsepower'].fillna(252.0)

In [29]:
df['horsepower'].median()

np.float64(252.0)

In [30]:
df_asia = df[df['origin']=='Asia']

In [32]:
df_asia[['vehicle_weight','model_year']].head(7)

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [35]:
X=df_asia[['vehicle_weight','model_year']].head(7).values
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [42]:
import numpy as np

def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [46]:
XTX = matrix_matrix_multiplication(X.T, X)
XTX

array([[1.3195050e+08, 6.0750580e+07],
       [6.0750580e+07, 2.8041424e+07]])

In [44]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [47]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [49]:
x_mult = matrix_matrix_multiplication(XTX_inv, X.T)
x_mult

array([[-2.50082897e-04, -1.65786806e-05, -2.86196661e-04,
         3.99964853e-04, -1.18162927e-03,  1.10298508e-03,
         2.25354894e-04],
       [ 6.12974614e-04,  1.06954785e-04,  6.91249245e-04,
        -7.95968736e-04,  2.63152339e-03, -2.31749941e-03,
        -4.16221392e-04]])

In [51]:
res = matrix_vector_multiplication(x_mult, y)
res

array([0.13644777, 0.2327492 ])

In [52]:
res.sum()

np.float64(0.3691969690492522)